CREATE TABLE `catalog_items` (
	`id` text PRIMARY KEY NOT NULL,
	`kind` text NOT NULL,
	`slug` text NOT NULL,
	`name` text NOT NULL,
	`summary` text NOT NULL,
	`description` text NOT NULL,
	`author_name` text NOT NULL,
	`author_handle` text NOT NULL,
	`author_verified` integer DEFAULT false NOT NULL,
	`source` text DEFAULT 'builtin' NOT NULL,
	`version` text DEFAULT '1.0.0' NOT NULL,
	`installs` integer DEFAULT 0 NOT NULL,
	`tags_json` text DEFAULT '[]' NOT NULL,
	`requires_json` text DEFAULT '[]' NOT NULL,
	`fields_json` text DEFAULT '[]' NOT NULL,
	`includes_json` text,
	`featured` integer DEFAULT false NOT NULL,
	`published` integer DEFAULT true NOT NULL,
	`provider` text,
	`has_webhook` integer DEFAULT false NOT NULL,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `catalog_items_slug_idx` ON `catalog_items` (`slug`);--> statement-breakpoint
CREATE INDEX `catalog_items_kind_idx` ON `catalog_items` (`kind`);--> statement-breakpoint
CREATE INDEX `catalog_items_source_idx` ON `catalog_items` (`source`);--> statement-breakpoint
CREATE INDEX `catalog_items_published_idx` ON `catalog_items` (`published`);--> statement-breakpoint
CREATE INDEX `catalog_items_featured_idx` ON `catalog_items` (`featured`);--> statement-breakpoint
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_agents` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text NOT NULL,
	`created_by_user_id` text,
	`name` text NOT NULL,
	`slug` text NOT NULL,
	`instructions` text DEFAULT '' NOT NULL,
	`model` text DEFAULT '@cf/moonshotai/kimi-k2.6' NOT NULL,
	`max_steps` integer DEFAULT 250 NOT NULL,
	`chat_recovery` integer DEFAULT true NOT NULL,
	`extensions` integer DEFAULT true NOT NULL,
	`execution_config_json` text DEFAULT '{"workspaceTools":true,"container":true,"browser":true}' NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`deployment_url` text,
	`latest_deployment_id` text,
	`last_run_at` integer,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	FOREIGN KEY (`organization_id`) REFERENCES `organizations`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`created_by_user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
INSERT INTO `__new_agents`("id", "organization_id", "created_by_user_id", "name", "slug", "instructions", "model", "max_steps", "chat_recovery", "extensions", "execution_config_json", "status", "deployment_url", "latest_deployment_id", "last_run_at", "created_at", "updated_at") SELECT "id", "organization_id", "created_by_user_id", "name", "slug", "instructions", "model", "max_steps", "chat_recovery", "extensions", "execution_config_json", "status", "deployment_url", "latest_deployment_id", "last_run_at", "created_at", "updated_at" FROM `agents`;--> statement-breakpoint
DROP TABLE `agents`;--> statement-breakpoint
ALTER TABLE `__new_agents` RENAME TO `agents`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `agents_slug_idx` ON `agents` (`slug`);--> statement-breakpoint
CREATE INDEX `agents_organization_status_idx` ON `agents` (`organization_id`,`status`);--> statement-breakpoint
CREATE INDEX `agents_created_by_user_idx` ON `agents` (`created_by_user_id`);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_ch_slack', 'channel', 'slack', 'Slack', 'Listen in channels and threads, reply as a bot user.', 'Install the agent into a Slack workspace. It can be mentioned in any channel it has been invited to, replies in-thread, and can post unprompted when a workflow tells it to.', 'crazp', 'crazp', 1, 'builtin', '2.4.0', 18420, '["chat","team"]', '[]', '[{"key":"botToken","label":"Bot token","type":"secret","required":true,"help":"Starts with xoxb-"},{"key":"signingSecret","label":"Signing secret","type":"secret","required":true},{"key":"defaultChannel","label":"Default channel","type":"text","required":false,"placeholder":"#support-inbox"}]', NULL, 1, 1, 'slack', 1, 1785825600000, 1785825600000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_ch_whatsapp', 'channel', 'whatsapp', 'WhatsApp', 'Answer messages sent to a WhatsApp Business number.', 'Connects through the WhatsApp Cloud API. Handles text, images and documents, which makes it the usual choice for agents that read invoices or receipts.', 'crazp', 'crazp', 1, 'builtin', '1.9.2', 9310, '["chat","support"]', '[]', '[{"key":"accessToken","label":"Access token","type":"secret","required":true},{"key":"phoneNumberId","label":"Phone number ID","type":"text","required":true,"placeholder":"1029384756"},{"key":"verifyToken","label":"Webhook verify token","type":"secret","required":true},{"key":"appSecret","label":"App secret","type":"secret","required":true,"help":"Meta app secret"}]', NULL, 0, 1, 'whatsapp', 1, 1784788800000, 1784788800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_ch_telegram', 'channel', 'telegram', 'Telegram', 'Run the agent as a Telegram bot, in DMs or groups.', 'The fastest channel to get working — create a bot with BotFather, paste the token, and the agent is reachable in under a minute.', 'crazp', 'crazp', 1, 'builtin', '1.4.0', 7880, '["chat"]', '[]', '[{"key":"botToken","label":"Bot token","type":"secret","required":true,"help":"From @BotFather"}]', NULL, 0, 1, 'telegram', 1, 1784011200000, 1784011200000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_ch_discord', 'channel', 'discord', 'Discord', 'Respond in servers, threads and DMs.', 'Useful for community support agents. Supports slash commands as well as mentions.', 'crazp', 'crazp', 1, 'builtin', '1.2.1', 4120, '["chat","community"]', '[]', '[{"key":"botToken","label":"Bot token","type":"secret","required":true},{"key":"applicationId","label":"Application ID","type":"text","required":true},{"key":"publicKey","label":"Public key","type":"secret","required":true,"help":"From Discord General Information"}]', NULL, 0, 1, 'discord', 1, 1783665600000, 1783665600000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_ch_email', 'channel', 'email', 'Email', 'Give the agent its own address and let it reply to threads.', 'Inbound mail is parsed into a conversation, so a long reply chain reads as one thread rather than six separate runs.', 'crazp', 'crazp', 1, 'builtin', '2.0.0', 11640, '["async","support"]', '[]', '[{"key":"address","label":"Address","type":"text","required":true,"placeholder":"help@yourdomain.com"},{"key":"providerToken","label":"Provider token","type":"secret","required":true,"help":"Postmark or Resend"}]', NULL, 0, 1, 'email', 0, 1785566400000, 1785566400000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_ch_web', 'channel', 'web-widget', 'Web widget', 'A embeddable chat bubble for your own site.', 'Drop one script tag into your site and the agent appears as a chat bubble. Appearance follows your brand colours; conversations show up in run history like any other channel.', 'crazp', 'crazp', 1, 'builtin', '3.1.0', 14050, '["web","embed"]', '[]', '[{"key":"allowedOrigins","label":"Allowed origins","type":"text","required":true,"placeholder":"https://northwind.co","help":"Comma separated. The widget refuses to load elsewhere."}]', NULL, 0, 1, 'web', 0, 1786171200000, 1786171200000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_ch_teams', 'channel', 'teams', 'Microsoft Teams', 'Reply in Teams chats and channels as a bot.', 'Connects through the Azure Bot Framework. Mention the agent in a channel or chat and it answers in-thread, same as Slack.', 'crazp', 'crazp', 1, 'builtin', '1.0.0', 2640, '["chat","team"]', '[]', '[{"key":"appId","label":"App ID","type":"text","required":true,"help":"Azure Bot / Microsoft App ID"},{"key":"appPassword","label":"App password","type":"secret","required":true},{"key":"appTenantId","label":"Tenant ID","type":"text","required":false}]', NULL, 0, 1, 'teams', 1, 1786430400000, 1786430400000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_ch_twilio', 'channel', 'twilio', 'Twilio', 'Send and receive SMS through a Twilio number.', 'Inbound texts become conversations. Use a phone number or a messaging service SID; the agent replies from the same identity.', 'crazp', 'crazp', 1, 'builtin', '1.0.0', 1980, '["sms","support"]', '[]', '[{"key":"accountSid","label":"Account SID","type":"text","required":true,"placeholder":"ACxxxxxxxx"},{"key":"authToken","label":"Auth token","type":"secret","required":true},{"key":"phoneNumber","label":"Phone number","type":"text","required":false,"placeholder":"+15551234567","help":"E.164. Required unless you set a messaging service SID."},{"key":"messagingServiceSid","label":"Messaging service SID","type":"text","required":false}]', NULL, 0, 1, 'twilio', 1, 1786344000000, 1786344000000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_ch_github', 'channel', 'github-channel', 'GitHub', 'Reply to mentions, issues, and pull request comments.', 'The agent shows up where your team already reviews code. A personal access token is enough to start; a GitHub App is the usual production setup.', 'crazp', 'crazp', 1, 'builtin', '1.0.0', 3210, '["dev","chat"]', '[]', '[{"key":"token","label":"Personal access token","type":"secret","required":true,"help":"Fine-grained or classic"},{"key":"webhookSecret","label":"Webhook secret","type":"secret","required":false}]', NULL, 0, 1, 'github', 1, 1786516800000, 1786516800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_ch_linear', 'channel', 'linear', 'Linear', 'Take issue comments and agent sessions from Linear.', 'Mention the agent on an issue or start an agent session. It reads the thread and can write back without leaving Linear.', 'crazp', 'crazp', 1, 'builtin', '1.0.0', 1470, '["dev","chat"]', '[]', '[{"key":"apiKey","label":"API key","type":"secret","required":true},{"key":"webhookSecret","label":"Webhook secret","type":"secret","required":false}]', NULL, 0, 1, 'linear', 1, 1786516800000, 1786516800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_ch_gchat', 'channel', 'gchat', 'Google Chat', 'Respond in Google Chat spaces as a Workspace bot.', 'Uses a service account from your Google Cloud project. Invite the bot to a space and it can be @mentioned like any other member.', 'crazp', 'crazp', 1, 'builtin', '1.0.0', 890, '["chat","team"]', '[]', '[{"key":"credentials","label":"Service account JSON","type":"secret","required":true,"help":"Paste the full key file contents."},{"key":"projectId","label":"Project ID","type":"text","required":false}]', NULL, 0, 1, 'gchat', 1, 1786257600000, 1786257600000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_ch_x', 'channel', 'x', 'X', 'Reply to mentions and DMs on X.', 'OAuth 2.0 with a refresh token. The agent answers mentions and direct messages from the account you connect.', 'crazp', 'crazp', 1, 'builtin', '1.0.0', 720, '["chat","social"]', '[]', '[{"key":"clientId","label":"Client ID","type":"text","required":true},{"key":"clientSecret","label":"Client secret","type":"secret","required":true},{"key":"consumerSecret","label":"Consumer secret","type":"secret","required":false},{"key":"refreshToken","label":"Refresh token","type":"secret","required":true}]', NULL, 0, 1, 'x', 1, 1786084800000, 1786084800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_ch_mcp', 'channel', 'mcp', 'MCP', 'Expose the agent as a Model Context Protocol endpoint.', 'A placeholder for MCP-as-channel until dedicated ingress lands. Clients should connect through the agent MCP connection surface in the meantime.', 'crazp', 'crazp', 1, 'builtin', '0.1.0', 310, '["mcp","dev"]', '[]', '[{"key":"instructions","label":"Instructions","type":"text","required":false,"help":"Optional extra policy for MCP turns."}]', NULL, 0, 1, 'mcp', 0, 1786516800000, 1786516800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_cn_zendesk', 'connection', 'zendesk', 'Zendesk', 'Read, create and assign tickets.', 'Authorise once with OAuth and the agent can open tickets, move them between queues, and read a customer''s history before it answers.', 'crazp', 'crazp', 1, 'builtin', '1.7.0', 6240, '["support","oauth"]', '[]', '[{"key":"subdomain","label":"Subdomain","type":"text","required":true,"placeholder":"northwind"},{"key":"scopes","label":"Scopes","type":"text","required":true,"placeholder":"tickets:write users:read"}]', NULL, 0, 1, NULL, 0, 1785220800000, 1785220800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_cn_stripe', 'connection', 'stripe', 'Stripe', 'Look up customers, charges and subscriptions.', 'Use a restricted key so the agent can read billing state without being able to move money. Refunds are a separate scope you have to grant deliberately.', 'crazp', 'crazp', 1, 'builtin', '2.2.0', 8970, '["billing"]', '[]', '[{"key":"restrictedKey","label":"Restricted key","type":"secret","required":true,"help":"Starts with rk_"},{"key":"scopes","label":"Scopes","type":"text","required":true,"placeholder":"customers:read charges:read"}]', NULL, 0, 1, NULL, 0, 1785998400000, 1785998400000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_cn_github', 'connection', 'github', 'GitHub', 'Read repositories, issues and pull requests.', 'Scoped to the repositories you pick. Most people pair this with the release-notes template.', 'crazp', 'crazp', 1, 'builtin', '1.5.3', 7410, '["dev","oauth"]', '[]', '[{"key":"repositories","label":"Repositories","type":"text","required":true,"placeholder":"northwind/api, northwind/web"}]', NULL, 0, 1, NULL, 0, 1784961600000, 1784961600000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_cn_hubspot', 'connection', 'hubspot', 'HubSpot', 'Read and update deals, contacts and companies.', 'Gives sales agents enough context to write a useful digest, and enough permission to log activity back onto the deal.', 'Priya Nair', 'priya', 0, 'community', '0.8.1', 1180, '["sales","crm"]', '[]', '[{"key":"privateAppToken","label":"Private app token","type":"secret","required":true}]', NULL, 0, 1, NULL, 0, 1784356800000, 1784356800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_cn_notion', 'connection', 'notion', 'Notion', 'Read pages and databases, append blocks.', 'Handy when your documentation lives in Notion and you want the agent to quote it rather than guess.', 'Tomas Vlk', 'tomas', 0, 'community', '1.1.0', 2640, '["docs"]', '[]', '[{"key":"integrationToken","label":"Integration token","type":"secret","required":true}]', NULL, 0, 1, NULL, 0, 1783060800000, 1783060800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_tl_web_search', 'tool', 'web-search', 'Web search', 'Search the public web and read the results.', 'Returns ranked results with a short extract from each page, so the agent can decide what to open rather than fetching everything.', 'crazp', 'crazp', 1, 'builtin', '1.0.0', 22900, '["research","builtin"]', '[]', '[]', NULL, 1, 1, NULL, 0, 1782456000000, 1782456000000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_tl_browser', 'tool', 'browser', 'Headless browser', 'Open a page, click things, and read what comes back.', 'For sites with no API. Runs in a sandbox with a per-run time limit; the agent gets the rendered text, not raw HTML.', 'crazp', 'crazp', 1, 'builtin', '1.6.0', 9640, '["automation","sandbox"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1785652800000, 1785652800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_tl_sql', 'tool', 'sql-query', 'SQL query', 'Run read-only queries against a database you connect.', 'Statements are parsed and rejected unless they are a single SELECT, so an agent cannot write even if it is asked to.', 'Marek Dolinski', 'marek', 0, 'community', '0.6.2', 3180, '["data"]', '[]', '[{"key":"connectionString","label":"Connection string","type":"secret","required":true},{"key":"maxRows","label":"Row limit","type":"text","required":false,"placeholder":"500"}]', NULL, 0, 1, NULL, 0, 1784616000000, 1784616000000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_tl_ticket', 'tool', 'create-ticket', 'Create ticket', 'Open a ticket and assign it to a queue.', 'Needs a support connection. The agent supplies a title, body and priority; the queue is either fixed here or chosen at run time.', 'crazp', 'crazp', 1, 'builtin', '1.3.0', 5870, '["support"]', '["zendesk"]', '[{"key":"defaultQueue","label":"Default queue","type":"text","required":false,"placeholder":"tier-1"}]', NULL, 0, 1, NULL, 0, 1785220800000, 1785220800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_tl_send_email', 'tool', 'send-email', 'Send email', 'Send a message from an address you own.', 'Separate from the email channel: this is the agent starting a conversation rather than replying to one.', 'crazp', 'crazp', 1, 'builtin', '1.1.0', 8120, '["async"]', '[]', '[{"key":"fromAddress","label":"From address","type":"text","required":true,"placeholder":"agent@northwind.co"}]', NULL, 0, 1, NULL, 0, 1784097600000, 1784097600000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_tl_pdf', 'tool', 'read-document', 'Read document', 'Pull text and tables out of a PDF or image.', 'Keeps table structure, which is what makes invoice and statement reading work at all.', 'Lena Fischer', 'lena', 0, 'community', '1.2.4', 4460, '["documents","ocr"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1785393600000, 1785393600000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_tl_calendar', 'tool', 'book-meeting', 'Book a meeting', 'Find free time and put something on a calendar.', 'Reads availability across the calendars you connect and writes the invite. It will never double-book without asking.', 'Sofia Márquez', 'sofia', 0, 'community', '0.9.0', 2050, '["scheduling"]', '[]', '[{"key":"calendarId","label":"Calendar","type":"text","required":true,"placeholder":"team@northwind.co"},{"key":"duration","label":"Default length","type":"select","options":["15 min","30 min","45 min","60 min"],"required":false}]', NULL, 0, 1, NULL, 0, 1783406400000, 1783406400000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_triage', 'skill', 'support-triage-rubric', 'Support triage rubric', 'Grade urgency from P0 to P3 consistently.', 'A written rubric with worked examples. Agents that use it stop calling everything urgent, which is the usual failure mode of a support agent.', 'crazp', 'crazp', 1, 'builtin', '1.4.0', 6730, '["support"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1785480000000, 1785480000000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_tone', 'skill', 'plain-language', 'Plain language', 'Write like a person, not a policy document.', 'Short sentences, no exclamation marks, name the problem before the fix. The most installed skill on the platform, for good reason.', 'crazp', 'crazp', 1, 'builtin', '2.0.1', 19880, '["writing"]', '[]', '[]', NULL, 1, 1, NULL, 0, 1786084800000, 1786084800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_refund', 'skill', 'refund-policy', 'Refund policy', 'When a refund is allowed and who has to approve it.', 'A starting point you are meant to edit — the thresholds are placeholders until you replace them with your own.', 'crazp', 'crazp', 1, 'builtin', '1.0.2', 3420, '["billing","policy"]', '[]', '[{"key":"windowDays","label":"Automatic window","type":"text","required":false,"placeholder":"14","help":"Days after purchase a refund needs no approval."}]', NULL, 0, 1, NULL, 0, 1783752000000, 1783752000000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_escalate', 'skill', 'escalation-brief', 'Escalation brief', 'Hand off to a human in four lines.', 'Teaches the agent to summarise a conversation the way an on-call engineer wants to receive it: what happened, what was tried, what is needed.', 'Dan Whitfield', 'dan', 0, 'community', '1.1.0', 2910, '["support","handoff"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1785048000000, 1785048000000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_rag', 'skill', 'cite-your-sources', 'Cite your sources', 'Quote the page, or say you don''t know.', 'Pairs with any documentation connection. Turns confident invention into a plain admission that the docs do not cover it.', 'crazp', 'crazp', 1, 'builtin', '1.2.0', 12240, '["docs","accuracy"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1785739200000, 1785739200000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_deescalate', 'skill', 'de-escalation', 'De-escalation', 'Lower the temperature before you try to solve anything.', 'Acknowledge the frustration in one sentence, then get specific. No ''I understand how you feel'' and no exclamation marks. Works on the tickets that would otherwise bounce to a human for tone alone.', 'crazp', 'crazp', 1, 'builtin', '1.3.0', 8410, '["support","writing"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1785912000000, 1785912000000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_privacy', 'skill', 'privacy-redaction', 'Privacy redaction', 'Never repeat a card number, address, or government ID.', 'Teaches the agent to recognise common PII, mask it in replies, and refuse to log it back into the conversation. Pair with any support or billing agent that sees customer records.', 'crazp', 'crazp', 1, 'builtin', '1.1.0', 5560, '["privacy","policy"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1784788800000, 1784788800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_qualify', 'skill', 'lead-qualification', 'Lead qualification', 'Ask BANT in a way that does not feel like a form.', 'Budget, authority, need, timing — in that order, but only after the prospect has said what they are trying to do. Stops the agent from pitching before it knows who it is talking to.', 'Priya Nair', 'priya', 0, 'community', '0.9.4', 1870, '["sales"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1785652800000, 1785652800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_notes', 'skill', 'meeting-notes', 'Meeting notes', 'Decisions, owners, and dates. Nothing else.', 'Turns a transcript into a one-page brief: what was decided, who owns it, and by when. Drops the recap of who said what, which nobody rereads.', 'crazp', 'crazp', 1, 'builtin', '1.0.0', 4980, '["writing","ops"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1786257600000, 1786257600000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_review', 'skill', 'code-review-voice', 'Code review voice', 'Comment on the diff, not the person.', 'Findings first, severity second, suggested patch last. No ''great job'' padding. Flags missing tests and silent error handling because those are the ones that ship.', 'Leo Park', 'leo', 0, 'community', '1.2.2', 3140, '["engineering"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1785220800000, 1785220800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_incident', 'skill', 'incident-status', 'Incident status', 'What is broken, who is affected, what we know.', 'A status-page voice: present tense, no speculation, no ''we apologise for the inconvenience''. Updates are additive so a later note never silently rewrites an earlier one.', 'crazp', 'crazp', 1, 'builtin', '1.5.0', 7220, '["ops","writing"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1786430400000, 1786430400000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_faq', 'skill', 'answer-from-faq', 'Answer from FAQ', 'Prefer the published answer over a clever paraphrase.', 'If the docs have a canonical reply, use it. If they do not, say so and offer to escalate. Stops the agent inventing a policy that sounds right.', 'crazp', 'crazp', 1, 'builtin', '1.0.3', 9050, '["docs","support"]', '["cite-your-sources"]', '[]', NULL, 0, 1, NULL, 0, 1784961600000, 1784961600000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_i18n', 'skill', 'reply-in-kind', 'Reply in kind', 'Match the customer''s language. Do not mix.', 'Detects the language of the latest message and stays in it, including error messages. Falls back to English only if it cannot tell, and says that it is doing so.', 'Marta Silva', 'marta', 0, 'community', '1.0.1', 2430, '["writing","support"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1784270400000, 1784270400000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_recovery', 'skill', 'service-recovery', 'Service recovery', 'Make it right without giving away the store.', 'When the company is at fault: apology, specific fix, what happens next. Credits and refunds stay inside the policy skill — this one is about the conversation, not the ledger.', 'crazp', 'crazp', 1, 'builtin', '1.1.1', 4670, '["support","billing"]', '["refund-policy"]', '[]', NULL, 0, 1, NULL, 0, 1785393600000, 1785393600000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_routing', 'skill', 'feature-request-routing', 'Feature request routing', 'Capture the ask, do not promise the roadmap.', 'Logs a feature request with the job to be done and how often it comes up. Never says ''I''ll pass this to the product team'' unless a ticket was actually opened.', 'Jonah Ellis', 'jonah', 0, 'community', '0.8.0', 1260, '["product","support"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1783147200000, 1783147200000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_churn', 'skill', 'save-the-account', 'Save the account', 'Ask why they are leaving before you discount.', 'A short save play: diagnose, offer the smallest relevant fix, then the pause, then the discount. Stops the agent from leading with 30% off every time someone types cancel.', 'crazp', 'crazp', 1, 'builtin', '1.2.0', 3890, '["billing","sales"]', '[]', '[{"key":"maxDiscount","label":"Max discount","type":"select","options":["10%","20%","30%"],"required":false,"help":"The agent will not go above this without a human."}]', NULL, 0, 1, NULL, 0, 1785825600000, 1785825600000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_onboard', 'skill', 'first-week-onboarding', 'First-week onboarding', 'One next step at a time, not a tour of every feature.', 'Picks the single most useful action for a new account and waits until it is done. The usual failure mode is a 12-bullet getting-started email nobody finishes.', 'crazp', 'crazp', 1, 'builtin', '1.0.0', 6110, '["product","writing"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1785998400000, 1785998400000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_legal', 'skill', 'do-not-advise', 'Do not advise', 'No legal, tax, or medical claims. Point to a human.', 'A hard stop for regulated questions. The agent names the domain, refuses to opine, and offers a specialist or a documented policy page instead.', 'crazp', 'crazp', 1, 'builtin', '2.1.0', 11040, '["policy","accuracy"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1786344000000, 1786344000000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sk_compete', 'skill', 'competitive-positioning', 'Competitive positioning', 'Compare on facts. Do not badmouth.', 'When a prospect names a competitor, answer with the documented differences and where the other product is a better fit. Invented knock-downs get agents uninstalled.', 'Asha Menon', 'asha', 0, 'community', '1.0.0', 1540, '["sales"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1784702400000, 1784702400000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sa_billing', 'subagent', 'billing-investigator', 'Billing investigator', 'Reconstructs a billing timeline for a disputed charge.', 'Given a customer, it walks the invoices and charges and explains what was billed when, without taking a side. Comes with its own narrow toolset.', 'crazp', 'crazp', 1, 'builtin', '1.3.0', 2180, '["billing"]', '["stripe"]', '[{"key":"model","label":"Model","type":"select","options":["@cf/moonshotai/kimi-k2.6","@cf/meta/llama-4-scout-17b"],"required":false}]', NULL, 0, 1, NULL, 0, 1785307200000, 1785307200000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sa_researcher', 'subagent', 'researcher', 'Researcher', 'Goes away, reads a lot, comes back with a summary.', 'Runs a longer loop than the parent agent so a slow question does not block a fast conversation.', 'crazp', 'crazp', 1, 'builtin', '1.0.0', 4620, '["research"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1784529600000, 1784529600000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_sa_translator', 'subagent', 'translator', 'Translator', 'Answers in the language the customer wrote in.', 'Detects the incoming language, translates the draft reply, and keeps product names untouched.', 'Yuki Tanaka', 'yuki', 0, 'community', '0.7.3', 1540, '["i18n"]', '[]', '[]', NULL, 0, 1, NULL, 0, 1783924800000, 1783924800000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_tp_support', 'template', 'support-triage', 'Support triage', 'Reads inbound support, answers the easy half, routes the rest.', 'The most common first agent. Arrives with a triage rubric, a tone-of-voice skill, ticket tooling and a Slack channel ready to configure.', 'crazp', 'crazp', 1, 'builtin', '2.1.0', 5910, '["support","popular"]', '[]', '[]', '["4 tools","2 skills","Slack channel","Zendesk connection","1 subagent"]', 1, 1, NULL, 0, 1785912000000, 1785912000000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_tp_release', 'template', 'release-notes', 'Release notes writer', 'Turns merged pull requests into notes a customer understands.', 'Wakes on a tag, reads the diff summaries, groups by user-visible outcome, and posts where your team already reads.', 'crazp', 'crazp', 1, 'builtin', '1.4.0', 2380, '["dev"]', '[]', '[]', '["3 tools","1 skill","GitHub connection","1 schedule"]', 0, 1, NULL, 0, 1784875200000, 1784875200000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_tp_docs', 'template', 'docs-answerer', 'Docs answerer', 'Answers product questions using only your documentation.', 'Ships with the cite-your-sources skill so it quotes a page or admits the gap, and a web widget so you can put it in your docs site the same day.', 'crazp', 'crazp', 1, 'builtin', '1.8.0', 4050, '["docs","popular"]', '[]', '[]', '["4 tools","5 skills","Web widget"]', 0, 1, NULL, 0, 1786257600000, 1786257600000);
--> statement-breakpoint
INSERT OR REPLACE INTO `catalog_items` (`id`, `kind`, `slug`, `name`, `summary`, `description`, `author_name`, `author_handle`, `author_verified`, `source`, `version`, `installs`, `tags_json`, `requires_json`, `fields_json`, `includes_json`, `featured`, `published`, `provider`, `has_webhook`, `created_at`, `updated_at`) VALUES ('cat_tp_invoice', 'template', 'invoice-reader', 'Invoice reader', 'Pulls line items out of invoices sent over WhatsApp.', 'Reads documents, checks the arithmetic, and flags anything where the total does not match the lines.', 'Lena Fischer', 'lena', 0, 'community', '1.0.1', 860, '["documents","finance"]', '[]', '[]', '["3 tools","WhatsApp channel"]', 0, 1, NULL, 0, 1784270400000, 1784270400000);
